# Generated by Django 6.0 on 2025-12-08 13:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_remove_savingsgoal_user_remove_transaction_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('owes_me', 'They Owe Me'), ('i_owe', 'I Owe Them')], max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
    ]
